### ISSUE TITLE
Circular import

### ISSUE THREAD

**Issue by michelegentili93** [netZoo/netZooPy#186]
Hi, I'm not sure if it's my environment causing the problem, but I can't import the package, due to a circular input:

```
ImportError                               Traceback (most recent call last)
<ipython-input-2-600f66c3916d> in <module>
      1 ##
----> 2 from netZooPy.panda.panda import Panda
      3 import pandas as pd
      4 import matplotlib.pyplot as plt
      5 import numpy as np

~/.conda/envs/pypandaenv1/lib/python3.8/site-packages/netZooPy/__init__.py in <module>
      1 from __future__ import absolute_import
      2 
----> 3 from netZooPy import panda
      4 from netZooPy import puma
      5 from netZooPy import lioness

ImportError: cannot import name 'panda' from partially initialized module 'netZooPy' (most likely due to a circular import) (/***/****/.conda/envs/pypandaenv1/lib/python3.8/site-packages/netZooPy/__init__.py)
```

on mi pip freeze I have one 1 version of netZooPy:
```
[...]
# Editable install with no version control (netZooPy==0.8)
-e /****/****/.conda/envs/pypandaenv1/lib/python3.8/site-packages
[...]
```

 installed from git has suggested :

pip install git+git://github.com/netZoo/netZooPy.git

What do you suggest?

**Comment by marouenbg** [comment]
Hi @michelegentili93 ,
It just did that and it worked for me. What it your OS? Please make sure you are using pip3.
Otherwise try the following
```
git clone https://github.com/netZoo/netZooPy.git
cd netZooPy
checkout devel
pip3 install -e .
```
and let me know!

**Comment by michelegentili93** [comment]
fixed! Thanks. :)

**Comment by thomasgilgenast** [comment]
For anyone else stumbling upon this issue thread:

I think the reason the "circular import" error occurs is actually because the subpackages of netZooPy are not listed in the `packages` kwarg of `setup()` in `setup.py` - only netZooPy itself is listed there. The result of this is that a regular (not editable) pip install of netZooPy only installs the netZooPy `__init__.py` - none of the subpackages get installed.

To illustrate (in a clean venv):

```
$ pip install git+https://github.com/netZoo/netZooPy
$ ls ./venv/lib/python3.8/site-packages/netZooPy
__init__.py
```

One solution is to use setuptools's `find_packages()` function (which is already imported in `setup.py`, but not called anywhere) to identify all the packages and subpackages automatically. By making [this commit](https://github.com/thomasgilgenast/netZooPy/commit/1b386a60f103564f6b31452363232c37bb54ddd1) on my fork of netZooPy it becomes possible to do:

```
$ pip install git+https://github.com/thomasgilgenast/netZooPy
$ ls ./venv/lib/python3.8/site-packages/netZooPy
__init__.py	condor		lioness		panda		sambar
__pycache__	dragon		otter		puma
$ python
>>> from netZooPy.panda.panda import Panda
```

with no issues - happy to open a PR with this commit if it would be helpful to have in the official repo.

**Comment by marouenbg** [comment]
Hi @thomasgilgenast ,
Thank you for figuring out this issue. It really surprising that It wasn't detected in the tests, this must be system-specific.
It would be great if you could open a PR on the devel branch with this fix. 
Thank you !

**Comment by thomasgilgenast** [comment]
Just opened a PR: #208

This doesn't get caught in CI because CI does

https://github.com/netZoo/netZooPy/blob/5424267fcf4320cc40bf258e1ac2caa0128bccf8/.github/workflows/main.yml#L33

which installs the package in dev mode. I think editable installs worked fine before (and after) this PR on any system - they don't depend on setuptools to copy any files into site-packages as part of the install process, instead they leave the entire source tree as-is and just make sure that the source folder is present in `sys.path`.

During a non-editable install (pip install without -e), setuptools/pip need to copy the correct source files into the correct part of site-packages, and setuptools relies on the `packages` kwarg of `setup()` to decide what to copy. (This is somewhat of an oversimplification but should be conceptually close enough.)

Really just a minor packaging quirk - sorry to stir up trouble over something so small.

**Comment by marouenbg** [comment]
Thank you so much @thomasgilgenast , I wasn't aware of the different install modes. Really appreciate your help!
