### ISSUE TITLE
condor results change when updating python-igraph to > 0.7.1.post6

### ISSUE THREAD

**Issue by marouenbg** [netZoo/netZooPy#82]
When python-igraph is updated to > 0.7.1.post6, the results of the community assignement changed in the unit test.
I temporarily set the version to 0.7.1.post6 in #81 but we need to investigate.
@genisott any ideas?

**Comment by genisott** [comment]
Hi Marouen,

I hope you are doing fine.

As far as I remember the only parts of the program that rely on igraph are
the reading of the network to build the graph object and the initial
community assignment, the rest is linear algebra that shouldn't change.

It is possible that the initial community assignment is a bit different if
they have updated their algorithms there, I will check what are the changes
in the different communities, but most probably it is one or two genes. The
python output differed from the R one in one or two, we assumed it was
because the initial community assignment was slightly different.

Nonetheless I will check as soon as I can. Thanks for letting me know.

Genís

**Comment by marouenbg** [comment]
Hi @genisott ,
Great to hear from you!
Thanks for clarifying this. Is there a way to get reproducible initial community assignments like setting a seed?
Stay safe out there!

**Comment by genisott** [comment]
Hi!

I will check as soon as I can. Unfortunately it might take a while, at the
moment I'm flooded with uni-related work. But I'll get to it soon enough.
I hope you are well,

Genís.

Missatge de Marouen <notifications@github.com> del dia dt., 28 d’abr. 2020
a les 2:34:

**Comment by marouenbg** [comment]
Sure !
Good luck with exams :)

**Comment by genisott** [comment]
Hi Marouen,

Sorry for this long delay. Now I'm working again at Marieke's lab and will
check this soon.

Thanks for your patience,

Genís.

Missatge de Marouen <notifications@github.com> del dia dj., 30 d’abr. 2020
a les 4:31:

**Comment by marouenbg** [comment]
Hello @genisott ,
So glad to have you back :)
Let me know how it goes!

**Comment by genisott** [comment]
Hi Marouen,

So far it seems that the community assignment doesn't change, at least with
the toy data. What has changed is the labelling. Communities coincide in
size and membership, just vary in name. It might be very hard to track
where this originates. I will check if the community assignment holds with
larger networks even if the labelling is different.
If it holds, could we consider updating the testing files?

Genís.

Missatge de Marouen <notifications@github.com> del dia ds., 11 de jul. 2020
a les 0:05:

**Comment by marouenbg** [comment]
Hi Genis,

Absolutely, if that makes sense to you.
It weird though, could setting the seed solve the issue?

Cheers,

**Comment by genisott** [comment]
I'm still checking, I don't really know what's changed.
Will let you know as soon as I know anything.

Genís.

Missatge de Marouen <notifications@github.com> del dia dc., 15 de jul. 2020
a les 5:39:

**Comment by genisott** [comment]
Okay, so as far as I have been able to see. They refactored part of their
community finding algorithms, nothing really new but perhaps memory
allocation has changed or something of the sort, it is really complicated.
I have checked the output of condor in every step and that was what
changed. I don't think there's a seed we can specify, just adapt to the new
library.
With the small toy networks the results coincide but the labelling doesn't.
With the big network there's some variation, but the number of communities
is consistent and most of the communities have the same nodes, the
modularity is also the same. This variation is due to the fact that with so
many nodes, the brim algorithm switches back and forth a lot of times  and
if it starts from a slightly different point it can end up giving a very
similar community assignment.
With this I would suggest adapting the testing file to this new version of
igraph, I think the results are consistent to a reasonable extent and the
program is still working.

Please let me know what you think,
Genís.

PS, I might be making a small update to condor, to introduce a new initial
community assignment method, if it gives good performance with the big
networks.

Missatge de Genís Calderer <genis.calderer@gmail.com> del dia dc., 15 de
jul. 2020 a les 11:29:

**Comment by marouenbg** [comment]
Hi Genis,

sounds good! I will post a note in case someone wants to reproduce the results of the earlier version.
If you want to update condor through a pull request, here is the [guide to follow](https://netzoo.github.io/contribute/contribute/), otherwise let's do it together through zoom at any time.

Thanks!

**Comment by marouenbg** [comment]
Condor ground truth changed to match behavior of python-igraph 0.8.2 in [netZooPy 0.7.2](https://github.com/netZoo/netZooPy/releases/tag/0.7.2)
